version: 0.0.{build}
image: Visual Studio 2019
skip_commits:
  message: /\[CI skip\]/
assembly_info:
  patch: true
  file: 'LSPD Paperwork\Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{branch}-{build}'
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
artifacts:
  - path: LSPD Paperwork\bin\$(configuration)\LSPD Paperwork.exe
    name: LSPDPaperwork

for:
-
  branches:
    only:
      - /\d+\.\d+\.\d+/
  version: '{branch}'
  deploy:
    - provider: GitHub
      tag: $(appveyor_build_version)
      release: LSPD Paperwork v$(appveyor_build_version)
      description: LSPD Paperwork Release.
      artifact: LSPDPaperwork
      draft: true
      force_update: true
      auth_token:
        secure: NdI/6/+ZUR7V9sTXlqHoXdhSASoRnwfCZTmC1iOVJ75TP3NsU/A+RDW9QDTtgqjN
