//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSPDPaperwork.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSPDPaperwork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white][img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=115]ARREST REPORT[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr][/hr]
        ///[float=right][b][size=115]MUGSHOT[/size][/b][/float][list=none][b][size=115]SUSPECT DETAILS[/size][/b]
        ///[list=none] [float=right] [fimg=200,185]__mugshot__[/fimg] [/float]
        ///
        ///[b]Full Name:[/b] __sus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArrestReport {
            get {
                return ResourceManager.GetString("ArrestReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GM01__Assault
        ///GM02__Battery
        ///GM03__Possession of a Blade
        ///GM04__Resisting Arrest
        ///GM05__Receiving Stolen Property
        ///GM06__Petty Theft
        ///GM07__Possession of a Fake Operator License or ID Card
        ///GM08__Identity Theft
        ///GM09__Vandalism
        ///GM10__Vigilantism
        ///GM11__Failure to Comply / Identify
        ///GM12__Predatory Lending
        ///GM13__Giving False Information to a Police Officer
        ///GM14__Criminal Threats
        ///GM15__Obstruction of Justice
        ///GM16__Animal Cruelty
        ///GM17__Failure to Pay a Fine
        ///GM18__Bribery
        ///GM19__Failure to Report the Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crimes {
            get {
                return ResourceManager.GetString("Crimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/afzUoXM.png[/img]
        ///
        ///[divbox=white]
        ///[b]Date:[/b] __date__
        ///[b]Hours on Duty: [/b] __dutyHours__
        ///[b]Start of watch: [/b] __watchStart__
        ///
        ///[b]Arrests:[/b] __arrests__
        ///[b]Citations:[/b] __citations__
        ///
        ///[b]Notes:[/b]
        ///__notes:My Default Content
        ///
        ///__
        ///
        ///[/divbox].
        /// </summary>
        internal static string DutyReport {
            get {
                return ResourceManager.GetString("DutyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white]
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=130]Firearms and Licensing Division[/size]
        ///[size=115]Application Response[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr]
        ///[list=none][b][i]Dear __applicant__[/i][/b],
        ///
        ///Your application has been received and acknowledged by the Firearms Licensing Division, Los Sant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FLDApproved {
            get {
                return ResourceManager.GetString("FLDApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white]
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=130]Firearms and Licensing Division[/size]
        ///[size=115]Application Response[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr]
        ///[list=none][b][i]Dear __applicant[/i][/b],
        ///
        ///Your application has been received and acknowledged by the Firearms Licensing Division, Los Santos [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FLDBkgndChk {
            get {
                return ResourceManager.GetString("FLDBkgndChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white]
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=130]Firearms and Licensing Division[/size]
        ///[size=115]Application Response[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr]
        ///[list=none][b][i]Dear __applicant__[/i][/b],
        ///
        ///Your application has been received and acknowledged by the Firearms Licensing Division, Los Sant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FLDIsOnHold {
            get {
                return ResourceManager.GetString("FLDIsOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white]
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=130]Firearms and Licensing Division[/size]
        ///[size=115]Application Response[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr]
        ///[list=none][b][i]Dear __applicant__[/i][/b],
        ///
        ///Your application has been received and acknowledged by the Firearms Licensing Division, Los Sant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FLDRejected {
            get {
                return ResourceManager.GetString("FLDRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img]
        ///[divbox=white]
        ///
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b][size=150]Los Santos Police Department[/size][/b]
        ///[size=115]Firearms and Licensing Division[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///
        ///[hr]
        ///[list=none]
        ///Gangs and Narcotics Division Detectives,
        ///
        ///Please complete a background check on __applicant__ to check for any gang affiliation you have on file. 
        ///Respond to this  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FLDReqBkgndChk {
            get {
                return ResourceManager.GetString("FLDReqBkgndChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgur.com
        ///gyazo.com
        ///cdn.discordapp.com
        ///dl.dropboxusercontent.com.
        /// </summary>
        internal static string ImgServices {
            get {
                return ResourceManager.GetString("ImgServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white]
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=115]IMPOUND RELEASE REPORT[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr][/hr]
        ///[list=none][b][size=115]VEHICLE DETAILS[/size][/b]
        ///[list=none]
        ///[b]Vehicle Owner:[/b] __vehOwner__
        ///[b]Phone Number:[/b] __phoneNum__
        ///[b]License Plate:[/b] __license__
        ///[b]Vehicle Model [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpoundRelease {
            get {
                return ResourceManager.GetString("ImpoundRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [img]https://i.imgur.com/88vzzHs.jpg[/img][divbox=white]
        ///[img]https://i.imgur.com/UYd15I0.png[/img][aligntable=right,0,0,0,0,0,0][right][font=Arial][b]
        ///[size=150]Los Santos Police Department[/size][/b]
        ///[size=115]IMPOUND REPORT[/size]
        ///[size=95]&quot;TO PROTECT AND SERVE&quot;[/size][/font][/right][/aligntable]
        ///[hr][/hr]
        ///[list=none][b][size=115]VEHICLE DETAILS[/size][/b]
        ///[list=none]
        ///[b]Vehicle Owner:[/b] __vehOwner__
        ///[b]Phone Number:[/b] __phoneNum__
        ///[b]License Plate:[/b] __license__
        ///[b]Vehicle Model:[/b] __ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImpoundReport {
            get {
                return ResourceManager.GetString("ImpoundReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A__A1__Name not in MDC.__We are unable to verify your name. Please correct it.__0
        ///A__A1__Name mismatch.__Your name does not match the other details provided. Please correct it.__0
        ///A__A2__Age Missing__You did not state your age. Please correct it__0
        ///A__A2__Underage__You are too young to possess a license ((Reapply with a proper age))__1
        ///A__A3__Phone # missing__You did not provide us with your phone number. Please correct it.__0
        ///A__A3__Phone # mismatch__We are unable to verify your phone number. Please c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rejections {
            get {
                return ResourceManager.GetString("Rejections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinghy
        ///Jetmax
        ///Kraken
        ///Marquis
        ///Police Predator
        ///Seashark
        ///Speeder
        ///Squalo
        ///Submersible
        ///Suntrap
        ///Toro
        ///Tropic
        ///Tug
        ///Benson
        ///Biff
        ///Cerberus
        ///Hauler
        ///Hauler Custom
        ///Mule
        ///Mule (Armored)
        ///Mule Custom
        ///Packer
        ///Phantom
        ///Phantom Custom
        ///Phantom Wedge
        ///Pounder
        ///Pounder Custom
        ///Stockade
        ///Tanker
        ///Terrorbyte
        ///Trailer
        ///Asbo
        ///Blista
        ///Blista Kanjo
        ///Brioso R/A
        ///Dilettante
        ///Issi
        ///Issi (Arena)
        ///Issi Classic
        ///Panto
        ///Prairie
        ///Rhapsody
        ///Cognescenti Cabrio
        ///Exemplar
        ///F620
        ///Felon
        ///Felon GT
        ///Jackal
        ///Oracle
        ///Oracle XS
        ///Sentinel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
    }
}
